version: '3'
services:
  go-bot:
    build: .
    environment:
      - SLACK_TOKEN=xoxb-568122985680-569209253669-2TgJ5LBcJP4mZCPfKWy3pJy6
    restart: always
networks:
  default:
    external:
      name: docker_network